-- TASK-0201 Today Migration
-- Create activity table (DATABASE_DESIGN §6.4 + L1 决策补充 daily_plan_id)
-- Owner: Today Module
--
-- L1 决策（AI_CHANGELOG 记录）：
--   DATABASE_DESIGN §6.4 activity 表未含 daily_plan_id 字段，但 daily_plan 1:N activity
--   是 Sprint 2 业务必需关系。本 Migration 补充 daily_plan_id BIGINT NOT NULL 字段
--   做逻辑关联。Decision Level: L1（表内 schema 完善，不改模块边界，不跨模块契约）。
--   不修改冻结的 DATABASE_DESIGN.md（Sprint 内），PR 描述 + AI_CHANGELOG 记录。
--
-- 枚举对齐 §7 ACTIVITY_TYPE: WORK / LEISURE / SPORT / STUDY / SOCIAL / EXPLORE / REST / OTHER
-- 外键策略：逻辑关联不建 FK (DATABASE_DESIGN §9)
-- location_id 逻辑关联 location.id（Explore Module, Sprint 3 创建，本 Sprint 可空）

CREATE TABLE IF NOT EXISTS activity
(
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    daily_plan_id   BIGINT       NOT NULL,
    title           VARCHAR(200) NOT NULL,
    type            VARCHAR(20)  NOT NULL DEFAULT 'OTHER',
    location_id     BIGINT,
    start_time      TIMESTAMP    NOT NULL,
    end_time        TIMESTAMP,
    created_time    TIMESTAMP    NOT NULL DEFAULT now(),
    updated_time    TIMESTAMP    NOT NULL DEFAULT now(),
    deleted_time    TIMESTAMP
);

COMMENT ON TABLE  activity IS '活动表 (DATABASE_DESIGN §6.4 + L1 补充 daily_plan_id, Owner: Today Module)';
COMMENT ON COLUMN activity.id             IS 'PK, 自增';
COMMENT ON COLUMN activity.daily_plan_id IS '逻辑关联 daily_plan.id（L1 决策补充，1:N 关系，不建物理 FK, DATABASE_DESIGN §9）';
COMMENT ON COLUMN activity.title          IS '活动标题';
COMMENT ON COLUMN activity.type           IS '活动类型 §7 ACTIVITY_TYPE: WORK/LEISURE/SPORT/STUDY/SOCIAL/EXPLORE/REST/OTHER';
COMMENT ON COLUMN activity.location_id    IS '逻辑关联 location.id（Explore Module, Sprint 3 创建，本 Sprint 可空）';
COMMENT ON COLUMN activity.start_time     IS '开始时间';
COMMENT ON COLUMN activity.end_time       IS '结束时间，可空';
COMMENT ON COLUMN activity.created_time    IS '创建时间';
COMMENT ON COLUMN activity.updated_time    IS '更新时间';
COMMENT ON COLUMN activity.deleted_time    IS '软删除时间，NULL 表示未删除';

-- 索引对齐 DATABASE_DESIGN §8
-- idx_activity_daily_plan：按计划查活动（L1 决策新增字段配套索引）
CREATE INDEX IF NOT EXISTS idx_activity_daily_plan
    ON activity (daily_plan_id)
    WHERE deleted_time IS NULL;

-- idx_activity_location：按地点查活动
CREATE INDEX IF NOT EXISTS idx_activity_location
    ON activity (location_id)
    WHERE location_id IS NOT NULL AND deleted_time IS NULL;

-- idx_activity_start_time：时间范围查询
CREATE INDEX IF NOT EXISTS idx_activity_start_time
    ON activity (start_time)
    WHERE deleted_time IS NULL;
