-- TASK-0004 Database Foundation
-- Create tag table (DATABASE_DESIGN §6.10)
-- Owner: Shared Kernel (ADR-0010 Proposed)
--
-- 注意：DATABASE_DESIGN §6.10 标注 Owner: User Module，但 ADR-0010 (Proposed)
-- 决策方向为 Tag 归 Shared Kernel。物理表创建归 TASK-0004，Owner 归属待 ADR-0010 正式 Accepted 后定稿。
--
-- 枚举对齐 §7 TAG_TYPE: INTEREST / SKILL / MOOD / GENERAL
-- 外键策略：逻辑关联不建 FK (DATABASE_DESIGN §9)
-- 唯一约束：(user_id, name, type) 防重复标签 (§8 uk_user_name_type)

CREATE TABLE IF NOT EXISTS tag
(
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT       NOT NULL,
    name          VARCHAR(50)  NOT NULL,
    type          VARCHAR(20)  NOT NULL DEFAULT 'GENERAL',
    created_time  TIMESTAMP    NOT NULL DEFAULT now()
);

COMMENT ON TABLE  tag IS '标签 (DATABASE_DESIGN §6.10, Owner 待 ADR-0010 定稿: Shared Kernel)';
COMMENT ON COLUMN tag.id            IS 'PK, 自增';
COMMENT ON COLUMN tag.user_id       IS '关联 user.id（逻辑关联，不建 FK）';
COMMENT ON COLUMN tag.name          IS '标签名';
COMMENT ON COLUMN tag.type          IS '标签类型 §7 TAG_TYPE: INTEREST/SKILL/MOOD/GENERAL';
COMMENT ON COLUMN tag.created_time  IS '创建时间';

-- 索引对齐 DATABASE_DESIGN §8: uk_user_name_type (UNIQUE)
CREATE UNIQUE INDEX IF NOT EXISTS uk_tag_user_name_type
    ON tag (user_id, name, type);
