-- TASK-0004 Database Foundation
-- Create user_preference table (DATABASE_DESIGN §6.2)
-- Owner: User Module
--
-- 枚举对齐 §7 BUDGET_LEVEL: LOW / MEDIUM / HIGH
-- 外键策略：逻辑关联不建 FK (DATABASE_DESIGN §9)
-- user_id 唯一约束：一用户一偏好 (§8 uk_user_preference_user_id)

CREATE TABLE IF NOT EXISTS user_preference
(
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT       NOT NULL,
    interest      VARCHAR(500),
    budget        VARCHAR(20)  DEFAULT 'MEDIUM',
    lifestyle     VARCHAR(500),
    created_time  TIMESTAMP    NOT NULL DEFAULT now(),
    updated_time  TIMESTAMP    NOT NULL DEFAULT now()
);

COMMENT ON TABLE  user_preference IS '用户偏好 (DATABASE_DESIGN §6.2, Owner: User Module)';
COMMENT ON COLUMN user_preference.id            IS 'PK, 自增';
COMMENT ON COLUMN user_preference.user_id       IS '关联 user.id（逻辑关联，不建 FK）';
COMMENT ON COLUMN user_preference.interest      IS '兴趣标签，逗号分隔';
COMMENT ON COLUMN user_preference.budget        IS '预算等级 §7 BUDGET_LEVEL: LOW/MEDIUM/HIGH';
COMMENT ON COLUMN user_preference.lifestyle     IS '生活方式描述';
COMMENT ON COLUMN user_preference.created_time  IS '创建时间';
COMMENT ON COLUMN user_preference.updated_time  IS '更新时间';

-- 索引对齐 DATABASE_DESIGN §8: uk_user_id (UNIQUE)
CREATE UNIQUE INDEX IF NOT EXISTS uk_user_preference_user_id
    ON user_preference (user_id);
