-- TASK-0004 Database Foundation
-- Create user table (DATABASE_DESIGN §6.1)
-- Owner: User Module
--
-- 枚举对齐 §7 USER_STATUS: ACTIVE / INACTIVE / BANNED
-- 外键策略：逻辑关联不建 FK (DATABASE_DESIGN §9)
-- email/phone 允许 NULL，非 NULL 时唯一 (§9 唯一约束)

CREATE TABLE IF NOT EXISTS "user"
(
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nickname      VARCHAR(50)  NOT NULL,
    avatar        VARCHAR(500),
    email         VARCHAR(100),
    phone         VARCHAR(20),
    city          VARCHAR(100),
    status        VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    created_time  TIMESTAMP    NOT NULL DEFAULT now(),
    updated_time  TIMESTAMP    NOT NULL DEFAULT now(),
    deleted_time  TIMESTAMP
);

COMMENT ON TABLE  "user" IS '用户主表 (DATABASE_DESIGN §6.1, Owner: User Module)';
COMMENT ON COLUMN "user".id            IS 'PK, 自增';
COMMENT ON COLUMN "user".nickname      IS '用户昵称';
COMMENT ON COLUMN "user".avatar        IS '头像 OSS 地址';
COMMENT ON COLUMN "user".email         IS '邮箱（登录凭证之一）';
COMMENT ON COLUMN "user".phone         IS '手机号（登录凭证之一）';
COMMENT ON COLUMN "user".city          IS '当前城市';
COMMENT ON COLUMN "user".status         IS '用户状态 §7 USER_STATUS: ACTIVE/INACTIVE/BANNED';
COMMENT ON COLUMN "user".created_time  IS '创建时间';
COMMENT ON COLUMN "user".updated_time  IS '更新时间';
COMMENT ON COLUMN "user".deleted_time  IS '软删除时间，NULL 表示未删除';

-- 索引对齐 DATABASE_DESIGN §8
-- uk_user_email / uk_user_phone：允许 NULL，非 NULL 时唯一
CREATE UNIQUE INDEX IF NOT EXISTS uk_user_email
    ON "user" (email)
    WHERE email IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uk_user_phone
    ON "user" (phone)
    WHERE phone IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_user_status
    ON "user" (status);
