-- TASK-0201 Today Migration
-- Create daily_plan table (DATABASE_DESIGN §6.3)
-- Owner: Today Module
--
-- 枚举对齐 §7 PLAN_STATUS: PLANNING / ONGOING / COMPLETED / CANCELLED
-- 外键策略：逻辑关联不建 FK (DATABASE_DESIGN §9)

CREATE TABLE IF NOT EXISTS daily_plan
(
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT       NOT NULL,
    date          DATE         NOT NULL,
    status        VARCHAR(20)  NOT NULL DEFAULT 'PLANNING',
    created_time  TIMESTAMP    NOT NULL DEFAULT now(),
    updated_time  TIMESTAMP    NOT NULL DEFAULT now(),
    deleted_time  TIMESTAMP
);

COMMENT ON TABLE  daily_plan IS '每日计划主表 (DATABASE_DESIGN §6.3, Owner: Today Module)';
COMMENT ON COLUMN daily_plan.id            IS 'PK, 自增';
COMMENT ON COLUMN daily_plan.user_id       IS '逻辑关联 user.id（不建物理 FK, DATABASE_DESIGN §9）';
COMMENT ON COLUMN daily_plan.date          IS '计划日期';
COMMENT ON COLUMN daily_plan.status        IS '计划状态 §7 PLAN_STATUS: PLANNING/ONGOING/COMPLETED/CANCELLED';
COMMENT ON COLUMN daily_plan.created_time  IS '创建时间';
COMMENT ON COLUMN daily_plan.updated_time  IS '更新时间';
COMMENT ON COLUMN daily_plan.deleted_time  IS '软删除时间，NULL 表示未删除';

-- 索引对齐 DATABASE_DESIGN §8 idx_user_date
CREATE INDEX IF NOT EXISTS idx_daily_plan_user_date
    ON daily_plan (user_id, date)
    WHERE deleted_time IS NULL;
