-- TASK-0301 Explore Migration
-- Create favorite table (DATABASE_DESIGN §6.7)
-- Owner: User Module
--
-- 枚举对齐 §7 FAVORITE_TARGET: LOCATION / ACTIVITY / ROUTE
-- 外键策略：逻辑关联不建 FK (DATABASE_DESIGN §9)
-- 唯一约束：(user_id, target_type, target_id) 防重复收藏 (§8 uk_user_target)
-- 无软删除：收藏为硬删除（取消收藏即物理删除）

CREATE TABLE IF NOT EXISTS favorite
(
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT       NOT NULL,
    target_type   VARCHAR(20)  NOT NULL,
    target_id     BIGINT       NOT NULL,
    created_time  TIMESTAMP    NOT NULL DEFAULT now()
);

COMMENT ON TABLE  favorite IS '收藏表 (DATABASE_DESIGN §6.7, Owner: User Module)';
COMMENT ON COLUMN favorite.id            IS 'PK, 自增';
COMMENT ON COLUMN favorite.user_id       IS '关联 user.id（逻辑关联，不建 FK）';
COMMENT ON COLUMN favorite.target_type   IS '收藏目标类型 §7 FAVORITE_TARGET: LOCATION/ACTIVITY/ROUTE';
COMMENT ON COLUMN favorite.target_id     IS '收藏目标 ID';
COMMENT ON COLUMN favorite.created_time  IS '创建时间';

-- 索引对齐 DATABASE_DESIGN §8: uk_user_target (UNIQUE)
CREATE UNIQUE INDEX IF NOT EXISTS uk_favorite_user_target
    ON favorite (user_id, target_type, target_id);

-- target_type CHECK 约束（DATABASE_DESIGN §7 FAVORITE_TARGET）
ALTER TABLE favorite
    DROP CONSTRAINT IF EXISTS chk_favorite_target_type;
ALTER TABLE favorite
    ADD CONSTRAINT chk_favorite_target_type
    CHECK (target_type IN ('LOCATION', 'ACTIVITY', 'ROUTE'));
