-- TASK-0301 Explore Migration
-- Create location table (DATABASE_DESIGN §6.9)
-- Owner: Explore Module
--
-- 枚举对齐 §7 LOCATION_TYPE: RESTAURANT / CAFE / PARK / MUSEUM / SHOPPING / SPORT / ENTERTAINMENT / SCENIC / OTHER
-- 外键策略：逻辑关联不建 FK (DATABASE_DESIGN §9)
-- 无软删除：location 表为公共参考数据，不做软删除

CREATE TABLE IF NOT EXISTS location
(
    id            BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(200)   NOT NULL,
    address       VARCHAR(500),
    city          VARCHAR(100)   NOT NULL,
    latitude      DECIMAL(10, 7) NOT NULL,
    longitude     DECIMAL(10, 7) NOT NULL,
    type          VARCHAR(20)    DEFAULT 'OTHER',
    created_time  TIMESTAMP      NOT NULL DEFAULT now(),
    updated_time  TIMESTAMP      NOT NULL DEFAULT now()
);

COMMENT ON TABLE  location IS '地点表 (DATABASE_DESIGN §6.9, Owner: Explore Module)';
COMMENT ON COLUMN location.id            IS 'PK, 自增';
COMMENT ON COLUMN location.name          IS '地点名称';
COMMENT ON COLUMN location.address       IS '详细地址';
COMMENT ON COLUMN location.city          IS '所属城市';
COMMENT ON COLUMN location.latitude      IS '纬度（10,7 精度）';
COMMENT ON COLUMN location.longitude     IS '经度（10,7 精度）';
COMMENT ON COLUMN location.type          IS '地点类型 §7 LOCATION_TYPE: RESTAURANT/CAFE/PARK/MUSEUM/SHOPPING/SPORT/ENTERTAINMENT/SCENIC/OTHER';
COMMENT ON COLUMN location.created_time  IS '创建时间';
COMMENT ON COLUMN location.updated_time  IS '更新时间';

-- 索引对齐 DATABASE_DESIGN §8
-- idx_city：按城市查询地点
CREATE INDEX IF NOT EXISTS idx_location_city
    ON location (city);

-- idx_lat_lng：地理范围查询（经纬度）
CREATE INDEX IF NOT EXISTS idx_location_lat_lng
    ON location (latitude, longitude);

-- type CHECK 约束（DATABASE_DESIGN §7 LOCATION_TYPE）
ALTER TABLE location
    DROP CONSTRAINT IF EXISTS chk_location_type;
ALTER TABLE location
    ADD CONSTRAINT chk_location_type
    CHECK (type IN ('RESTAURANT', 'CAFE', 'PARK', 'MUSEUM', 'SHOPPING', 'SPORT', 'ENTERTAINMENT', 'SCENIC', 'OTHER'));
